on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ryboster/unity-project-builder-ghcr:latest
      credentials:
        username: ${{ secrets.ACCESS_UNAME }}
        password: ${{ secrets.ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          git -c safe.directory='*' checkout origin/dev
          unity -quit -batchmode \
          -executeMethod brewing-game.Builder.BuildProject \
          -outputPath . \
          -buildTarget Linux